name: "turaew.io"
description: "Personal website of Paul Turaew built with Jekyll and Bootstrap"

url: "http://localhost:4000"

# paginate: 3
# paginate_path: "blog/page:num/"

markdown: kramdown
permalink: pretty
